--문제4
--같은 직급의 평균급여보다 같거나 많은 급여를 받는 직원의 이름, 직급코드, 급여, 급여등급 조회
SELECT EMP_NAME "직원명", DEPT_CODE "직급코드", SALARY "급여", SAL_LEVEL "급여등급"
FROM EMPLOYEE E
JOIN SAL_GRADE USING(SAL_LEVEL);

-- 각 직급의 평균
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

-- 4번 답
SELECT EMP_NAME "직원명", DEPT_CODE "직급코드", SALARY "급여", SAL_LEVEL "급여등급"
FROM EMPLOYEE E
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEE WHERE E.JOB_CODE = JOB_CODE);

--문제5
--부서별 평균 급여가 2200000 이상인 부서명, 평균 급여 조회
--단, 평균 급여는 소수점 버림, 부서명이 없는 경우 '인턴'처리
SELECT NVL(DEPT_TITLE, '인턴') "부서명", FLOOR(SUM(SALARY)) "평균급여"
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE
-- GROUP BY 부서명
HAVING FLOOR(SUM(SALARY)) >= 2200000;
--HAVING 평균급여 >= 2200000;

-- 5번 답
SELECT NVL((SELECT DEPT_TITLE FROM DEPARTMENT WHERE DEPT_ID=EMPLOYEE.DEPT_CODE),'인턴') 부서명
        ,FLOOR(AVG(SALARY)) 평균급여
FROM EMPLOYEE GROUP BY DEPT_CODE
HAVING AVG(SALARY) >= 2200000;


--문제6
--직급의 연봉 평균보다 적게 받는 여자사원의
--사원명,직급명,부서명,연봉을 이름 오름차순으로 조회하시오
--연봉 계산 => (급여+(급여*보너스))*12    
-- 사원명,직급명,부서명,연봉은 EMPLOYEE 테이블을 통해 출력이 가능함
SELECT EMP_NAME "사원명", DEPT_TITLE "직급명", DEPT_TITLE "부서명",
(SALARY+(SALARY*NVL(BONUS,0))*12) "연봉"
FROM EMPLOYEE E
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
WHERE SUBSTR(EMP_NO,8,1) IN ('2','4') 
AND E.SALARY > (SELECT SUM(SALARY) FROM EMPLOYEE WHERE E.DEPT_ID=DEPT_ID GROUP BY DEPT_TITLE)
ORDER BY 1;

SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_TITLE;


-- 6번 답
SELECT EMP_NAME 사원명
        , JOB_NAME 직급
        , DEPT_TITLE 부서명
        , (SALARY+SALARY*NVL(BONUS,0))*12 연봉 
FROM EMPLOYEE E LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
    LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE (SALARY+SALARY*NVL(BONUS,0))*12 < (SELECT AVG((SALARY+SALARY*NVL(BONUS,0))*12) FROM EMPLOYEE WHERE E.JOB_CODE=JOB_CODE)
    AND SUBSTR(EMP_NO,8,1) IN (2,4)
ORDER BY 1 ASC;
