-- 실습문제
-- kh계정 소유의 한 employee, job, department테이블의 일부정보를 사용자에게 공개하려고 한다
-- 사원아이디, 사원명, 직급명, 부서명, 관리자명, 입사일의 컬럼정보를 뷰(v_emp_info)를 
-- (읽기전용) 생성
CREATE VIEW V_EMP_INFO
AS SELECT E.EMP_ID "사원아이디", E.EMP_NAME "사원명",
JOB_NAME "직급명", DEPT_TITLE "부서명", E.HIRE_DATE "입사일"
FROM EMPLOYEE E
LEFT JOIN JOB USING(JOB_CODE)
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

SELECT * FROM V_EMP_INFO;
DROP VIEW V_EMP_INFO;

CREATE OR REPLACE VIEW V_EMP_INFO
AS SELECT E.EMP_ID "사원아이디", E.EMP_NAME "사원명",
JOB_NAME "직급명", DEPT_TITLE "부서명", M.EMP_NAME"관리자명", E.HIRE_DATE "입사일"
FROM EMPLOYEE E
LEFT JOIN JOB USING(JOB_CODE)
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
LEFT JOIN EMPLOYEE M ON M.EMP_ID = E.MANAGER_ID
WITH READ ONLY;

SELECT * FROM V_EMP_INFO;
DROP VIEW V_EMP_INFO;

-- VIEW 옵션
-- VIEW를 만든 후에 수정해야될 경우 삭제 후 재생성 해야함
-- 1. OR REPLACE
-- -> 생성한 뷰가 존재하면 뷰를 갱신해준다
CREATE OR REPLACE VIEW V_EMP_INFO
AS SELECT E.EMP_ID "사원아이디", E.EMP_NAME "사원명",
JOB_NAME "직급명", DEPT_TITLE "부서명", M.EMP_NAME"관리자명", E.HIRE_DATE "입사일"
FROM EMPLOYEE E
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN EMPLOYEE M ON M.EMP_ID = E.MANAGER_ID;

-- OR REPLACE가 항상 가능한것은 아님
-- FORCE/NOFORCE
-- 기본값은 NOFORCE로 되어있음
CREATE OR REPLACE FORCE VIEW V_FORCE_SOMETHING
AS SELECT EMP_ID, EMP_NO FROM NOTHINHG_TBL;

-- View생성하기
CREATE OR REPLACE VIEW V_EMPLOYEE
AS SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE
FROM EMPLOYEE
WITH READ ONLY;
-- 읽기 전용으로 만듬

-- VIEW수정
-- 42399.0000 - "cannot perform a DML operation on a read-only view"
UPDATE V_EMPLOYEE
SET DEPT_CODE = 'D8'
WHERE EMP_ID = 200;

-- WITH CHECK OPTION
-- -> WHERE절 조건에 사용한 컬럼의 값을 수정하지 못하게함
CREATE OR REPLACE VIEW V_EMP_D5
AS SELECT EMP_ID, EMP_NAME, SALARY, DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5' WITH CHECK OPTION;

-- WHERE절 조건에 포함이 되어서 update불가능
UPDATE V_EMP_D5 SET DEPT_CODE = 'D2'
WHERE SALARY >= 2500000;

-- WHERE절 조건에 포함이 안되어서 update가능
UPDATE V_EMP_D5 SET EMP_NAME = '선동렬'
WHERE SALARY >= 800000;