-- SELECT
SELECT EMP_ID, EMP_NAME, EMP_NO
FROM EMPLOYEE;

-- NULL이면 계산을 못함
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12)
FROM EMPLOYEE;

-- 별칭 지정 가능
-- as " "
-- as는 생략 가능
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) AS "연봉(보너스 포함)"
FROM EMPLOYEE;
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE;

-- WHERE로 조건식도 가능
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000;

-- WHERE로 조건식 AND OR도 가능
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 AND EMP_NAME = '선동일';

SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY < 1000000 OR EMP_NAME = '선동일';

-- 정렬 ORDER BY
-- ORDER BY는 제일 마지막에 실행!
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 OR EMP_NAME = '선동일'
ORDER BY SALARY ASC;

SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 OR EMP_NAME = '선동일'
ORDER BY EMP_NAME ASC;

-- ASC일때 null은 제일 마지막에
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 OR EMP_NAME = '선동일'
ORDER BY BONUS ASC;

-- DESC일때 null은 제일 위에
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 OR EMP_NAME = '선동일'
ORDER BY BONUS DESC;

-- 정렬 내림차순
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY > 3000000 OR EMP_NAME = '선동일'
ORDER BY SALARY DESC;

-- BETWEEN A AND B, 연산자
SELECT EMP_NAME, SALARY, SALARY*12, BONUS, (SALARY*BONUS + SALARY*12) "연봉(보너스 포함)"
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 6000000;

SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D6' OR DEPT_CODE = 'D8';

-- 위 코드를 간편하게
SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D6', 'D8');

SELECT EMP_NAME, SALARY, BONUS
FROM EMPLOYEE
--WHERE BONUS IS NOT NULL;
WHERE BONUS IS NULL;

-- LIKE 연산자
-- 전씨 성을 가진 직원의 이름과 급여를 조회
-- 와일드카드 필요
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
--WHERE EMP_NAME LIKE '전%';
-- 전으로 시작하는건 전부 다. 전도 포함
WHERE EMP_NAME LIKE '%전%';
-- 전이 들어가는건 전부
--WHERE EMP_NAME LIKE '%전';
-- 전으로 끝나는건 모두

-- EMPLOYEE 테이블에서 이름이 끝이 연으로 끝나는 사원의 이름을 출력하시오
-- 와일드 카드
-- 1. % : 0개 이상의 모든 문자를 매칭
-- 2. _(언더바) : 하나의 자리에 해당하는 모든 문자를 매칭
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '__연';



-- 실습문제
--1. EMPLOYEE 테이블에서 이름 끝이 연으로 끝나는 사원의 이름을 출력하시오
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '__연';

--2. EMPLOYEE 테이블에서 전화번호 처음 3자리가 010이 아닌 사원의 이름, 전화번호를
--출력하시오
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

--3. EMPLOYEE 테이블에서 메일주소의 's'가 들어가면서, DEPT_CODE가 D9 또는 D6이고
--고용일이 90/01/01 ~ 01/12/01이면서, 월급이 270만원이상인 사원의 전체 정보를 출력하시오
SELECT * 
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/12/01'
AND EMAIL LIKE '%s%'
AND SALARY >= 2700000
--AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6');
AND DEPT_CODE IN ('D9', 'D6');

--4. EMPLOYEE 테이블에서 EMAIL ID 중 @ 앞자리가 5자리인 직원을 조회한다면?
SELECT EMP_NAME
FROM EMPLOYEE
--WHERE EMAIL LIKE '_____@';
WHERE EMAIL LIKE '_____@%';

--5. EMPLOYEE 테이블에서 EMAIL ID 중 '_' 앞자리가 3자리인 직원을 조회한다면?
--SELECT EMP_NAME
--FROM EMPLOYEE
--WHERE EAMAIL LIKE '___';
-- 수업시간외에 배운 내용을 사용 해야함.

--6. 관리자(MANAGER_ID)도 없고 부서 배치(DEPT_CODE)도 받지 않은  직원의 이름 조회
SELECT EMP_NAME
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL AND DEPT_CODE IS NULL;

--7. 부서배치를 받지 않았지만 보너스를 지급하는 직원 전체 정보 조회
SELECT *
FROM EMPLOYEE
WHERE DEPT_CODE IS NULL AND BONUS IS NOT NULL;

--8. EMPLOYEE 테이블에서 이름,연봉, 총수령액(보너스포함), 실수령액(총 수령액-(월급*세금 3%*12))가 출력되도록 하시오
SELECT EMP_NAME "이름",SALARY*12 "연봉", SALARY*12*(1+BONUS) "총수령액(보너스포함)",
(SALARY*12*(1+BONUS)-(SALARY*0.03*12)) "실수령액"
FROM EMPLOYEE;

--9. EMPLOYEE 테이블에서 이름, 근무 일수를 출력해보시오.(SYSDATE를 사용하면 현재 시간 출력)
SELECT EMP_NAME, SYSDATE-HIRE_DATE
FROM EMPLOYEE;
-- 나중에 함수를 통해서 소수점 제거해볼것!

--10. EMPLOYEE 테이블에서 20년 이상 근속자의 이름,월급,보너스율를 출력하시오.
SELECT EMP_NAME, SALARY, BONUS
FROM EMPLOYEE
WHERE SYSDATE-HIRE_DATE >= 20 * 365;